import Navbar from "./Component/Navbar";
import "./globals.css";
import Footer from "./Component/Footer";

export const metadata = {
  title: "First Choice Afro Villa Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
